language: php

addons:
  apt:
    packages:
      - libxml2-utils

php:
  - 7.1

env:
  global:
    - DEFAULT_COMPOSER_FLAGS="--no-interaction --no-ansi --no-progress --no-suggest"

before_install:
  - ./tools/composer clear-cache

install:
    travis_retry ./tools/composer update $DEFAULT_COMPOSER_FLAGS

before_script:
  - echo 'assert.exception=On' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

script:
  - ./vendor/bin/phpunit --coverage-clover=coverage.xml
  - ./vendor/bin/phpunit --configuration ./build/travis-ci-fail.xml > /dev/null; if [ $? -eq 0 ]; then echo "SHOULD FAIL"; false; else echo "fail checked"; fi;
  - xmllint --noout --schema phpunit.xsd phpunit.xml
  - xmllint --noout --schema phpunit.xsd test/_files/configuration.xml
  - xmllint --noout --schema phpunit.xsd test/_files/configuration_empty.xml
  - xmllint --noout --schema phpunit.xsd test/_files/configuration_xinclude.xml -xinclude

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: true