language: php

addons:
  apt:
    packages:
      - libxml2-utils

php:
  - 7.1

env:
  global:
    - DEFAULT_COMPOSER_FLAGS="--no-interaction --no-ansi --no-progress --no-suggest"

before_install:
  - ./tools/composer clear-cache

install:
    travis_retry ./tools/composer update $DEFAULT_COMPOSER_FLAGS

before_script:
  - echo 'assert.exception=On' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

script:
  - ./vendor/bin/phpunit --printer=Codedungeon\\PHPUnitPrettyResultPrinter\\Printer --coverage-clover=coverage.xml test/*

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: true